// apps/web/src/components/UserList.svelte
<script lang="ts">
  import UserListItem from "./UserListItem.svelte";

  import type { MongoDBUser } from "../app";

  export let title: string;
  export let users: (Pick<MongoDBUser, "username" | "image"> & Partial<Pick<MongoDBUser, "image" | "_id">>)[];
</script>

<aside class="border-light-gray dark:border-semi-gray h-full w-full overflow-y-auto rounded-xl border-2 bg-white dark:bg-black">
  <section class="flex w-full items-center bg-white p-2 dark:bg-black">
    <h1 class="ml-2 mt-2 hidden text-xl font-medium min-[500px]:block">{title}</h1>
  </section>
  <section role="list">
    {#each users as { username, image }}
      <UserListItem {username} {image} />
    {/each}
  </section>
</aside>

// apps/web/src/components/UserList.tsx
import type { MongoDBUser } from "@/types";
import type { FC } from "react";

import UserListItem from "@/components/UserListItem";

interface Props {
  title: string;
  users: Pick<MongoDBUser, "username" | "image">[];
}

const UserList: FC<Props> = ({ title, users }) => (
  <aside className="border-light-gray dark:border-semi-gray h-full w-full overflow-y-auto rounded-xl border-2 bg-white dark:bg-black">
    <section className="flex w-full items-center bg-white p-2 dark:bg-black">
      <h1 className="ml-2 mt-2 hidden text-xl font-medium min-[500px]:block">{title}</h1>
    </section>
    <section role="list">
      {users.map((user: Pick<MongoDBUser, "username" | "image">, index: number) => (
        <UserListItem key={`${user.username}:${index}`} {...user} />
      ))}
    </section>
  </aside>
);

export default UserList;
