// apps/web/src/routes/people/[name]/+page.svelte
<script lang="ts">
  import Image from "../../../components/Image.svelte";
  import PostList from "../../../components/PostList.svelte";

  import { getHandle } from "../../../utils/globals";

  export let data;

  const { username, image } = data.profileUser;
</script>

<svelte:head>
  <title>{username}'s Profile</title>
  <meta name="description" content="Visit {username} on Tea Share." />
  <meta name="og:title" content="{username}'s Profile" />
  <meta name="og:description" content="Visit {username} on Tea Share." />
  <meta name="og:image" content={image} />
  <meta name="og:image:width" content="600" />
  <meta name="og:image:height" content="600" />
  <meta name="twitter:title" content="{username}'s Profile" />
  <meta name="twitter:description" content="Visit {username} on Tea Share." />
  <meta name="twitter:image" content={image} />
  <meta name="twitter:image:alt" content={username} />
</svelte:head>

<article class="grid h-screen place-items-center overflow-y-auto">
  <article
    class="border-light-gray dark:border-semi-gray mt-10 flex w-[80%] flex-col items-center rounded-md border-2 bg-white p-12 dark:bg-black sm:ml-5 md:ml-0 md:w-[30%] md:flex-row md:items-start lg:w-1/2"
  >
    <Image src={image} alt={username} height={130} width={130} class="h-[130px] rounded-full" />
    <div class="mt-4 text-center md:ml-8 md:mt-0 md:text-start">
      <h1 class="text-3xl font-bold">{username}</h1>
      <h2 class="text-xl text-gray-400">{getHandle(username)}</h2>
      <h3 class="mt-2 text-xl">
        {data.posts.length} Posts By {username}
      </h3>
    </div>
  </article>
  <div class="mt-6 w-[90%]">
    <PostList posts={data.posts} />
  </div>
</article>

// web/pages/users/[name].tsx
import React, { useEffect } from "react";
import type { ProfileProps, Post } from "../../types";
import type { NextPage, GetServerSideProps } from "next";
import { useRouter } from "next/router";
import dynamic from "next/dynamic";

import { fetchPostByQuery, fetchUserByQuery } from "../../api";

import Sidebar from "../../components/Sidebar";
const Post = dynamic(() => import("../../components/Post"));
const Image = dynamic(() => import("next/image"));

const Profile: NextPage<ProfileProps> = ({ user, posts }) => {
  const { username, image } = user;

  const router = useRouter();

  useEffect(() => {
    const user = JSON.parse(localStorage.getItem("user") as string);

    if (!user?.displayName) router.push(`/users/${user?.displayName}`);
  }, []);

  return (
    <section className="flex h-screen dark:bg-black dark:text-white">
      <Sidebar route="profile" />
      <article className="h-full w-[82%] overflow-y-auto">
        <div className="flex flex-col items-center">
          <div className="mt-[50px] flex w-[80%] flex-col items-center rounded-md bg-light-gray p-12 dark:bg-dark-gray sm:ml-5 md:ml-0 md:w-[30%] md:flex-row md:items-start lg:w-1/2">
            {user ? (
              <>
                <Image src={image} alt={username} height={130} width={130} className="rounded-full" />
                <div className="mt-4 text-center md:mt-0 md:ml-8 md:text-start">
                  <h1 className="text-3xl font-bold">{username}</h1>
                  <h2 className="text-xl text-gray-500">@{username?.toLowerCase()?.split(" ")?.join("-")}</h2>
                  <h3 className="mt-2 text-xl">
                    Posts by {username} ({posts?.length})
                  </h3>
                </div>
              </>
            ) : (
              <h1 className="text-3xl font-bold">Loading user...</h1>
            )}
          </div>
          <aside className="mt-6 grid grid-cols-1 place-items-center xl:grid-cols-2">
            {posts?.map(post => (
              <Post key={post._id} post={post} />
            ))}
          </aside>
        </div>
      </article>
    </section>
  );
};

export const getServerSideProps: GetServerSideProps<ProfileProps> = async ({ params }) => {
  const { data: posts } = await fetchPostByQuery(`${params?.name}`);
  const { data: user } = await fetchUserByQuery(`${params?.name}`);

  return {
    props: { user, posts },
  };
};

export default Profile;
