// apps/web/src/routes/people/[name]/+page.svelte
<script lang="ts">
  import Image from "../../../components/Image.svelte";
  import PostList from "../../../components/PostList.svelte";

  import { getHandle } from "../../../utils/globals";

  export let data;

  const { username, image } = data.profileUser;
</script>

<svelte:head>
  <title>{username}'s Profile</title>
  <meta name="description" content="Visit {username} on Tea Share." />
  <meta name="og:title" content="{username}'s Profile" />
  <meta name="og:description" content="Visit {username} on Tea Share." />
  <meta name="og:image" content={image} />
  <meta name="og:image:width" content="600" />
  <meta name="og:image:height" content="600" />
  <meta name="twitter:title" content="{username}'s Profile" />
  <meta name="twitter:description" content="Visit {username} on Tea Share." />
  <meta name="twitter:image" content={image} />
  <meta name="twitter:image:alt" content={username} />
</svelte:head>

<article class="grid h-screen place-items-center overflow-y-auto">
  <article
    class="border-light-gray dark:border-semi-gray mt-10 flex w-[80%] flex-col items-center rounded-md border-2 bg-white p-12 dark:bg-black sm:ml-5 md:ml-0 md:w-[30%] md:flex-row md:items-start lg:w-1/2"
  >
    <Image src={image} alt={username} height={130} width={130} class="h-[130px] rounded-full" />
    <div class="mt-4 text-center md:ml-8 md:mt-0 md:text-start">
      <h1 class="text-3xl font-bold">{username}</h1>
      <h2 class="text-xl text-gray-400">{getHandle(username)}</h2>
      <h3 class="mt-2 text-xl">
        {data.posts.length} Posts By {username}
      </h3>
    </div>
  </article>
  <div class="mt-6 w-[90%]">
    <PostList posts={data.posts} />
  </div>
</article>

// web/pages/post/author/[name].tsx
import { useEffect } from "react";
import { useRouter } from "next/router";
import dynamic from "next/dynamic";

import type { NextPage, GetServerSideProps } from "next";
import type { MongoDBUser, Post, PostAuthorProps } from "../../../types";

const Sidebar = dynamic(() => import("../../../components/Sidebar"));
const Post = dynamic(() => import("../../../components/Post"));
const Image = dynamic(() => import("next/image"));

const Author: NextPage<PostAuthorProps> = ({ user, posts }) => {
  const { username, image } = user;

  const router = useRouter();
  const { post } = router.query;

  useEffect(() => {
    if (!user) location.reload();
  }, []);

  return (
    <section className="flex h-screen bg-white dark:bg-dark-gray dark:text-white">
      <Sidebar route="post-author-info" isOnPostInfo={{ visible: true, title: "View Post", href: `/post/${post}`, postedBy: username }} />
      <article className="h-full w-[82%] overflow-y-auto">
        <div className="flex flex-col items-center">
          <div className="mt-[50px] flex w-[80%] flex-col items-center rounded-md border-2 border-light-gray bg-white p-12 dark:border-border-gray dark:bg-black sm:ml-5 md:ml-0 md:w-[30%] md:flex-row md:items-start lg:w-1/2">
            {user ? (
              <>
                <Image src={image} alt={username} height={130} width={130} className="h-[130px] rounded-full" />
                <div className="mt-4 text-center md:mt-0 md:ml-8 md:text-start">
                  <h1 className="text-3xl font-bold">{username}</h1>
                  <h2 className="text-xl text-gray-500">@{username?.toLowerCase().split(" ").join("-")}</h2>
                  <h3 className="mt-2 text-xl">
                    Posts by {username} ({posts?.length})
                  </h3>
                </div>
              </>
            ) : (
              <h1 className="text-3xl font-bold">Loading user...</h1>
            )}
          </div>
          <aside className="mt-6 mr-10 grid grid-cols-1 place-items-center sm:mr-0 xl:grid-cols-2">
            {posts?.map(post => (
              <Post key={post._id} post={post} />
            ))}
          </aside>
        </div>
      </article>
    </section>
  );
};

export const getServerSideProps: GetServerSideProps<PostAuthorProps> = async ({ params }) => {
  const { fetchUserByQuery, fetchPostByQuery } = await import("../../../api");

  const [posts, user]: [Post[], MongoDBUser] = await Promise.all([
    fetchPostByQuery(params?.name as string),
    fetchUserByQuery(params?.name as string),
  ]);

  return {
    props: { user, posts },
  };
};

export default Author;
